#更新fork
name: update fork

on:
  schedule:
    - cron: '0 0 * * *' #0点定时任务

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != 'HapeLee/legado-with-MD3'
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Set env
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
    - name: Update fork
      run: |
        git remote add upstream https://github.com/HapeLee/legado-with-MD3.git
        git remote -v
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
